horizon_s: 2.0
dt_s: 0.01
mus: [0.3, 0.5, 0.8]
v0_kph: [30, 60, 120]
eta_beta: 0.95
eta_r: 0.95
eta_ltr: 0.95
eta_ax: 0.95
eps_v_mps: 0.5
ltr_max_abs: 0.95
vehicle:
  m_kg: 1400.0
  Iz_kgm2: 1800.0
  lf_m: 1.2
  lr_m: 1.3
  track_m: 1.55
  h_cg_m: 0.55
  Cf0_Nprad_front: 1.2e5
  Cr0_Nprad_rear: 1.0e5

  L_m: 4.60
  W_m: 1.85
  ego_margin_m: 0.20


bins:
  v_mps: [0, 10, 20, 30, 50]
  psi_rad: [-0.6, -0.2, 0.2, 0.6]
alpha:
  value: auto         # 或具体数值；auto 时用 optimizealpha
  min_pts_alpha: 8    # 少于 8 个点不用 alpha，直接凸包
  buffer_eps_m: 0.05  # 退化缓冲 5 cm
  min_area_m2: 0.001  # 面积小于 1e-3 m^2 时补缓冲

#s2t:
#  area_eps_m2: 0.10     # 07a：每帧需要的“可走余量面积”阈值
#  frac_thr: 0.75        # 07a：窗口内 ≥90% 帧满足面积阈值才算 OK
#  roi_radius_m: 12.0    # 07a/07b：只在障碍<=15m 的帧上评估（避免 t=0 泡泡）

s2t:
  area_eps_m2:  0.13    # 每帧留空面积阈值 ↑（原 0.10/0.20 之间试探）
  frac_thr:     0.85    # 窗口内 ≥90% 帧满足才算 OK
  roi_radius_m: 14.0    # 评估窗口回到 15m（或 16~18m，再严一些）

tube:
  erosion_m: 0.20     # 负 buffer 蚀刻半径（m），↑ 更保守（降 FP）
  min_area_m2: 0.02   # 过滤面积阈值（m²），↑ 也更保守