horizon_s: 2.0
dt_s: 0.01
mus:
- 0.3
- 0.5
- 0.8
v0_kph:
- 30
- 60
- 120
eta_beta: 0.95
eta_r: 0.95
eta_ltr: 0.95
eta_ax: 0.95
eps_v_mps: 0.5
ltr_max_abs: 0.95
vehicle:
  m_kg: 1413.0
  Iz_kgm2: 1579.092
  lf_m: 1.015
  lr_m: 1.895
  track_m: 1.54
  h_cg_m: 0.54
  Cf0_Nprad_front: 120000.0
  Cr0_Nprad_rear: 100000.0
  L_m: 4.6
  W_m: 1.85
  ego_margin_m: 0.2
bins:
  v_mps:
  - 0
  - 10
  - 20
  - 30
  - 50
  psi_rad:
  - -0.6
  - -0.2
  - 0.2
  - 0.6
alpha:
  value: auto
  min_pts_alpha: 8
  buffer_eps_m: 0.05
  min_area_m2: 0.001
tube:
  erosion_m: 0.0
  min_area_m2: 0.0
s2t:
  area_eps_m2: 0.13
  frac_thr: 0.85
  roi_radius_m: 14
